[package]
name = "wanggen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

png = "0.17.1"
palette = "0.2.1"
assert_hex = "0.2.2"